# 分页设置放在gems的最后
gems: ["github-pages", "jekyll-paginate"]

# 最新文章显示几篇
paginate: 3
emoji:
  src: "/assets/images/emojis"
permalink: /:year/:month/:day/:title.html


# 目前版本不再推荐redcarpet
markdown: kramdown

# 我的宏定义
zhehua:
  home: http://zhehua.info
  images: http://zhehua.info/assets/images
  emoji: http://zhehua.info/assets/images/emojis


# 作者信息
author:
  name: Zhehua
  email: zhehua@zhehua.info
  link: http://zhehua.info
  github: https://github.com/Zhehua-Hu
  weibo: http://weibo.com/huzhehua
  linkedin: https://www.linkedin.com/in/zhehua

# 站点信息
title: 哲华的博客
description: Zhehua's Blog
url: http://zhehua.info
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /assets/images/blog/EnchainLogoLittle.ico
favicon: /assets/images/blog/EnchainLogoLittle.ico



# 主题设置，自动激活某个标签
active: 博文心

# 首页除了最新文章外显示分类
cates: 
  - 博客必读


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# 插件设置

# google analytics 设置
# 不用修改_includes/googleanalytics.html
ga:
  id: UA-92998021-1
  url: zhehua.info

# disqus 设置
comments: true
disqus:
  shortname: zhehua

#permalink: /:year/:month/:day/:title.html