permalink: /:year/:month/:day/:title.html
#分页设置
gems: [jekyll-paginate]

paginate: 5

# 目前版本不再推荐redcarpet
markdown: kramdown
# encoding: utf-8

zhehua:
  cdn:../../../assets/files/EnchainLogoLittle.ico

mcdn: ../../../assets/files/EnchainLogoLittle.ico

# gems: ["jemoji"]

# /*1ABC9C blue #268bd2 */
 #/*16A085 to green #859900 */
# /*base #073642 */
#/*#E5F7F3 #31708F*/

# 作者信息
author:
  name: Zhehua
  email: zhehua@zhehua.info
  link: http://zhehua.info
  github: https://github.com/Zhehua-Hu
  weibo: http://weibo.com/huzhehua
  linkedin: https://www.linkedin.com/in/zhehua

# 站点信息
title: 哲华的博客
description: Zhehua's Blog
url: http://zhehua.info
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/blog/EnchainLogoLittle.ico
favicon: /public/img/blog/EnchainLogoLittle.ico



# 主题设置，自动激活某个标签
active: 博文心

# 首页除了最新文章外显示分类
cates: 
  - 博客必读

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# 插件设置

# google analytics 设置
# 不用修改_includes/googleanalytics.html
ga:
  id: UA-92998021-1
  url: zhehua.info

# disqus 设置
comments: true
disqus:
  shortname: zhehua

