permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown


# 作者信息
author:
  name: Anya Lin
  email: zhehua@zhehua.info
  link: http://zhehua.info
  github: https://github.com/Zhehua-Hu
  weibo: http://weibo.com/huzhehua
  linkedin: https://www.linkedin.com/in/zhehua

# 站点信息
title: 哲华的博客
description: Zhehua's Blog
url: http://zhehua.info
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/blog/EnchainLogoLittle.ico
favicon: /public/img/blog/EnchainLogoLittle.ico

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com


# 主题设置，自动激活某个标签
active: 博文心

# 首页除了最新文章外显示分类
cates: 
  - 博客必读


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档